/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team_management;

import java.awt.Color;
import javax.swing.JOptionPane;
import static team_management.dashboard.accountsTable;

/**
 *
 * @author ALka Media
 */
public class accounts extends javax.swing.JFrame {
    Codes co=new Codes();
    public void display(){
    
}    String idacc="";
     String oper="";

    /**
     * Creates new form accounts
     */
    public accounts() {
        initComponents();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnclose = new necesario.LabelIcon();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtaccountsBalance = new RSMaterialComponent.RSTextFieldIconTwo();
        txtaccountsName = new RSMaterialComponent.RSTextFieldIconTwo();
        txtinstAccounts = new RSMaterialComponent.RSTextFieldIconTwo();
        btnSave = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtaccountsser = new RSMaterialComponent.RSTextFieldIconTwo();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnclose.setBackground(new java.awt.Color(0, 102, 102));
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR);
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncloseMouseExited(evt);
            }
        });
        jPanel2.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/READY7.png"))); // NOI18N
        jLabel1.setText("   Accounts");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 310, 90));

        jLabel6.setBackground(new java.awt.Color(0, 102, 102));
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("AccName");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Institution");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 100, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("Balance");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 80, 30));

        txtaccountsBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtaccountsBalance.setBorderColor(new java.awt.Color(0, 102, 102));
        txtaccountsBalance.setColorIcon(new java.awt.Color(0, 153, 153));
        txtaccountsBalance.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MONETIZATION_ON);
        txtaccountsBalance.setPlaceholder("Enter balance");
        jPanel2.add(txtaccountsBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 270, -1));

        txtaccountsName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtaccountsName.setBorderColor(new java.awt.Color(0, 102, 102));
        txtaccountsName.setColorIcon(new java.awt.Color(0, 153, 153));
        txtaccountsName.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PEOPLE);
        txtaccountsName.setPlaceholder("ENTER ACCOUNT NAME");
        jPanel2.add(txtaccountsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 270, -1));

        txtinstAccounts.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtinstAccounts.setBorderColor(new java.awt.Color(0, 102, 102));
        txtinstAccounts.setColorIcon(new java.awt.Color(0, 153, 153));
        txtinstAccounts.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BUSINESS);
        txtinstAccounts.setPlaceholder("ENTER BANK ");
        jPanel2.add(txtinstAccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 270, -1));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (21).png"))); // NOI18N
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 90, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (22).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 110, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (25).png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 100, 40));

        txtaccountsser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtaccountsser.setBorderColor(new java.awt.Color(0, 102, 102));
        txtaccountsser.setColorIcon(new java.awt.Color(0, 153, 153));
        txtaccountsser.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtaccountsser.setPlaceholder("type Here To  Search");
        txtaccountsser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccountsserActionPerformed(evt);
            }
        });
        jPanel2.add(txtaccountsser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 230, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (26).png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 110, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/people.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 460, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
        // TODO add your handling code here:
        this.hide();
        //d.show();
    }//GEN-LAST:event_btncloseMouseClicked

    private void btncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseEntered
        // TODO add your handling code here:
         Color clr = new Color(0,153,153);
        btnclose.setBackground(clr);
    }//GEN-LAST:event_btncloseMouseEntered

    private void btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        btnclose.setBackground(clr);
    }//GEN-LAST:event_btncloseMouseExited

    private void txtaccountsserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccountsserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccountsserActionPerformed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
        
               String oper="insert";
        String sql="call accounts_proc(null,'"+txtaccountsName.getText()+"', '"+txtinstAccounts.getText()+"', '"+txtaccountsBalance.getText()+"','"+oper+"')";
      co.setSQL(sql);
      display();
      txtaccountsName.setText("");  txtinstAccounts.setText("");  txtaccountsBalance.setText("");
        co.viewTable("select * from accounts",accountsTable);
        
        
    }//GEN-LAST:event_btnSaveMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        
        String oper="update";
        String sql="call accounts_proc('"+idacc+"','"+txtaccountsName.getText()+"','"+txtinstAccounts.getText()+"','"+txtaccountsBalance.getText()+"','"+oper+"')";
      co.setSQL(sql);
      display();
      txtaccountsName.setText("");  txtinstAccounts.setText("");  txtaccountsBalance.setText("");
      co.viewTable("select * from accounts",accountsTable);
      btnSave.setEnabled(true);
      
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        
                if(JOptionPane.showConfirmDialog(null, "ma hubtaa","xaqiijin",
                     JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
        String oper="delete";
        String sql="call accounts_proc('"+idacc+"','"+txtaccountsName.getText()+"','"+txtinstAccounts.getText()+"','"+txtaccountsBalance.getText()+"','"+oper+"')";
             
      co.setSQL(sql);
      display();
      txtaccountsName.setText("");  txtinstAccounts.setText(""); txtaccountsBalance.setText("");
      co.viewTable("select * from accounts",accountsTable);
             }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
         String sql="select * from accounts where accName='"+txtaccountsser.getText()+"' or acc_no='"+txtaccountsser.getText()+"'";
     co.search(sql);
     try{
         if(co.rs.next()){
             idacc=co.rs.getString("acc_no");
             txtaccountsName.setText(co.rs.getString("accName"));
             txtinstAccounts.setText(co.rs.getString("institution"));
             txtaccountsBalance.setText(co.rs.getString("balance"));
             btnSave.setEnabled(false);
             txtaccountsser.setText("");
         }
         else
             JOptionPane.showMessageDialog(null, "Xogtaan Lama Helin");
            txtaccountsser.setText("");
     }catch(Exception ex){
         JOptionPane.showMessageDialog(null, ex.getMessage());
     }
        
                           
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accounts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSave;
    private necesario.LabelIcon btnclose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private RSMaterialComponent.RSTextFieldIconTwo txtaccountsBalance;
    private RSMaterialComponent.RSTextFieldIconTwo txtaccountsName;
    private RSMaterialComponent.RSTextFieldIconTwo txtaccountsser;
    private RSMaterialComponent.RSTextFieldIconTwo txtinstAccounts;
    // End of variables declaration//GEN-END:variables
}
