package team_management;

import java.awt.Color;
import java.sql.Date;
import javax.swing.JOptionPane;
import static team_management.dashboard.activityTable;

/**
 *
 * @author ALka Media
 */
public class activites extends javax.swing.JFrame {
      Codes co=new Codes();
    public void display(){
}    String idac="";
     String oper="";

    /**
     * Creates new form activites
     */
    public activites() {
        initComponents();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnclose = new necesario.LabelIcon();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtactivityname = new app.bolivia.swing.JCTextField();
        jLabel11 = new javax.swing.JLabel();
        txtactivtyDesc = new app.bolivia.swing.JCTextField();
        jLabel13 = new javax.swing.JLabel();
        jDateActivities = new com.toedter.calendar.JDateChooser();
        btnsave = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtseractivity = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnclose.setBackground(new java.awt.Color(0, 102, 102));
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR);
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncloseMouseExited(evt);
            }
        });
        jPanel2.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/READY8.png"))); // NOI18N
        jLabel1.setText("   Activities");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 430, 90));

        jLabel6.setBackground(new java.awt.Color(0, 102, 102));
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 90));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("ActivityName");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, 30));

        txtactivityname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtactivityname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtactivityname.setPhColor(new java.awt.Color(0, 102, 102));
        txtactivityname.setPlaceholder("Enter Acc_Name");
        txtactivityname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtactivitynameActionPerformed(evt);
            }
        });
        jPanel2.add(txtactivityname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 230, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("ActDesc");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 100, 30));

        txtactivtyDesc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtactivtyDesc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtactivtyDesc.setPhColor(new java.awt.Color(0, 102, 102));
        txtactivtyDesc.setPlaceholder("Enter institution");
        txtactivtyDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtactivtyDescActionPerformed(evt);
            }
        });
        jPanel2.add(txtactivtyDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 230, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("ActDate");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 100, 30));

        jDateActivities.setForeground(new java.awt.Color(0, 102, 102));
        jDateActivities.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jDateActivities, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, 40));

        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (21).png"))); // NOI18N
        btnsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsaveMouseClicked(evt);
            }
        });
        jPanel2.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 90, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (22).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 110, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (25).png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 100, 40));

        txtseractivity.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtseractivity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtseractivity.setPhColor(new java.awt.Color(0, 102, 102));
        txtseractivity.setPlaceholder("Enter Acc_Name");
        txtseractivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtseractivityActionPerformed(evt);
            }
        });
        jPanel2.add(txtseractivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 230, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (26).png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, 40));

        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 410, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/jobimage2.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 460, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
        // TODO add your handling code here:
         this.hide();
    }//GEN-LAST:event_btncloseMouseClicked

    private void txtactivitynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtactivitynameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtactivitynameActionPerformed

    private void txtactivtyDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtactivtyDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtactivtyDescActionPerformed

    private void btncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        btnclose.setBackground(clr);
    }//GEN-LAST:event_btncloseMouseEntered

    private void btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        btnclose.setBackground(clr);
    }//GEN-LAST:event_btncloseMouseExited

    private void txtseractivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtseractivityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtseractivityActionPerformed

    private void btnsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseClicked
        // TODO add your handling code here:
         String oper="insert";
        Date dl = new Date(jDateActivities.getDate().getTime());
        String sql="Call Activity_proc(null,'"+txtactivityname.getText()+"', '"+txtactivtyDesc.getText()+"','"+dl+"','"+oper+"')";
      co.setSQL(sql);
      display();
      txtactivityname.setText("");  txtactivtyDesc.setText("");
        co.viewTable("select * from activites", activityTable);
    }//GEN-LAST:event_btnsaveMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        String oper="update";
        Date dl=new Date(jDateActivities.getDate().getTime());
        String sql="Call activity_proc('"+idac+"','"+txtactivityname.getText()+"', '"+txtactivtyDesc.getText()+"','"+dl+"','"+oper+"')";
      co.setSQL(sql);
      display();
      txtactivityname.setText("");  txtactivtyDesc.setText("");
        co.viewTable("select * from activites", activityTable);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
            if(JOptionPane.showConfirmDialog(null, "ma hubtaa","xaqiijin",
                     JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
        String oper="delete";
        Date dl=new Date(jDateActivities.getDate().getTime());
        String sql="Call activity_proc('"+idac+"','"+txtactivityname.getText()+"', '"+txtactivtyDesc.getText()+"','"+dl+"','"+oper+"')";
      co.setSQL(sql);
      display();
      txtactivityname.setText("");  txtactivtyDesc.setText(""); 
      btnsave.setEnabled(true);
        co.viewTable("select * from activites", activityTable);
    }//GEN-LAST:event_jLabel4MouseClicked
    }
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
         String sql="select * from activites where activityName='"+txtseractivity.getText()+"'or act_no='"+txtseractivity.getText()+"'";
        co.search(sql);
     try{
         if(co.rs.next()){
             idac=co.rs.getString("act_no");
             txtactivityname.setText(co.rs.getString("activityName"));
             txtactivtyDesc.setText(co.rs.getString("ActivityDesc"));
             jDateActivities.setDate(co.rs.getDate("ActivityDate"));
             btnsave.setEnabled(false);
             txtseractivity.setText("");
         }
         else
             JOptionPane.showMessageDialog(null, "Xogtaan Lama Helin");
            txtseractivity.setText("");
     }catch(Exception ex){
         JOptionPane.showMessageDialog(null, ex.getMessage());
     }
    }//GEN-LAST:event_jLabel5MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(activites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(activites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(activites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(activites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new activites().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private necesario.LabelIcon btnclose;
    private javax.swing.JLabel btnsave;
    private com.toedter.calendar.JDateChooser jDateActivities;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private app.bolivia.swing.JCTextField txtactivityname;
    private app.bolivia.swing.JCTextField txtactivtyDesc;
    private app.bolivia.swing.JCTextField txtseractivity;
    // End of variables declaration//GEN-END:variables
}
