/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team_management;

import java.awt.Color;
import java.sql.Date;
import javax.swing.JOptionPane;
import static team_management.dashboard.billsTableview;

/**
 *
 * @author ALka Media
 */
public class  Bills extends javax.swing.JFrame {
     Codes co=new Codes();
    public void display(){
}    String idbil="";
     String billspep="";
     String amount ="";
     String desc ="";
     String oper="";

    /**
     * Creates new form Bills
     */
    public Bills() {
        initComponents();
        display();
        co.fillCombo("SELECT pepname as  'pep_Name' FROM people",billspeople_no,"pep_Name");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCTextField1 = new app.bolivia.swing.JCTextField();
        jCTextField2 = new app.bolivia.swing.JCTextField();
        jLabel4 = new javax.swing.JLabel();
        jCTextField3 = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        btnclose = new necesario.LabelIcon();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDateBillDates = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtAmountBills = new app.bolivia.swing.JCTextField();
        jLabel10 = new javax.swing.JLabel();
        txtdescriptionBills = new app.bolivia.swing.JCTextField();
        billspeople_no = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtserbill = new app.bolivia.swing.JCTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bills");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("people");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 160, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Description");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 160, 80));

        jCTextField1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jCTextField1.setPlaceholder("xog so gali");
        jCTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 230, 30));

        jCTextField2.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jCTextField2.setPlaceholder("xog so gali");
        jCTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 138, 220, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 160, 80));

        jCTextField3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jCTextField3.setPlaceholder("xog so gali");
        jCTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 230, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Amount");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 160, 80));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 230, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 340, 250));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelTextIcon1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelTextIcon1.setText("Bills");
        rSLabelTextIcon1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_BALANCE);
        jPanel2.add(rSLabelTextIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 210, 50));

        btnclose.setBackground(new java.awt.Color(0, 153, 153));
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR);
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncloseMouseExited(evt);
            }
        });
        jPanel2.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 30, 30));

        jLabel6.setBackground(new java.awt.Color(0, 153, 153));
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("peopleNo");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("BillDate");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, 30));
        jPanel2.add(jDateBillDates, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 260, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Amount");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 80, 30));

        txtAmountBills.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAmountBills.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAmountBills.setPhColor(new java.awt.Color(0, 102, 102));
        txtAmountBills.setPlaceholder("Enter Amount");
        txtAmountBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountBillsActionPerformed(evt);
            }
        });
        jPanel2.add(txtAmountBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 260, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Desc");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 60, 30));

        txtdescriptionBills.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdescriptionBills.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdescriptionBills.setPhColor(new java.awt.Color(0, 102, 102));
        txtdescriptionBills.setPlaceholder("Enter Name");
        txtdescriptionBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescriptionBillsActionPerformed(evt);
            }
        });
        jPanel2.add(txtdescriptionBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 260, 40));

        billspeople_no.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select person" }));
        billspeople_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billspeople_noActionPerformed(evt);
            }
        });
        jPanel2.add(billspeople_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 260, 40));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (21).png"))); // NOI18N
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 90, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (22).png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 110, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (25).png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 100, 40));

        txtserbill.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtserbill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtserbill.setPhColor(new java.awt.Color(0, 102, 102));
        txtserbill.setPlaceholder("Type Here To Search");
        txtserbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserbillActionPerformed(evt);
            }
        });
        jPanel2.add(txtserbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 190, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (26).png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 100, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/people1.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 480, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField1ActionPerformed

    private void jCTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField2ActionPerformed

    private void jCTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField3ActionPerformed

    private void txtAmountBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountBillsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountBillsActionPerformed

    private void txtdescriptionBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescriptionBillsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescriptionBillsActionPerformed

    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_btncloseMouseClicked

    private void btncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        btnclose.setBackground(clr);
    }//GEN-LAST:event_btncloseMouseEntered

    private void btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        btnclose.setBackground(clr);
    }//GEN-LAST:event_btncloseMouseExited

    private void billspeople_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billspeople_noActionPerformed
        // TODO add your handling code here:
        
        try{ 
          co.search("SELECT * FROM people WHERE pepname='"+billspeople_no.getSelectedItem()+"'");
         if(co.rs.next()){
             billspep=co.rs.getString("people_no");
             
         }
          }
       catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex.getMessage());
       }
        
        
    }//GEN-LAST:event_billspeople_noActionPerformed

    private void txtserbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserbillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserbillActionPerformed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
        
         String oper="insert";
        Date dl=new Date(jDateBillDates.getDate().getTime());
        String sql="call bills_proc(null,'"+billspep+"','"+txtAmountBills.getText()+"','"+dl+"','"+txtdescriptionBills.getText()+"','"+oper+"')";
        if(billspeople_no.getSelectedIndex()==0||txtAmountBills.getText().isEmpty() || txtdescriptionBills.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please Fill the Spaces");
        }
        else{
        co.setSQL(sql);
        display();
        //txtserbill.setText(sql);
        txtAmountBills.setText(""); txtdescriptionBills.setText(""); billspeople_no.setSelectedIndex(0);
        co.viewTable("select * from bills_view",billsTableview);
        
        }
    }//GEN-LAST:event_btnSaveMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        
        String oper="update";
        Date dl=new Date(jDateBillDates.getDate().getTime());
        String sql="call bills_proc('"+idbil+"','"+billspep+"','"+txtAmountBills.getText()+"','"+dl+"','"+txtdescriptionBills.getText()+"','"+oper+"')";
        co.setSQL(sql);
        display();
        //txtserbill.setText(sql);
        txtAmountBills.setText(""); txtdescriptionBills.setText(""); billspeople_no.setSelectedIndex(0);
        co.viewTable("select * from bills_view",billsTableview);
        
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "ma hubtaa","xaqiijin",
                     JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
        String oper="delete";
        Date dl=new Date(jDateBillDates.getDate().getTime());
        String sql="call bills_proc('"+idbil+"','"+billspep+"','"+txtAmountBills.getText()+"','"+dl+"','"+txtdescriptionBills.getText()+"','"+oper+"')";
        co.setSQL(sql);
        display();
        //txtserbill.setText(sql);
        txtAmountBills.setText(""); txtdescriptionBills.setText(""); billspeople_no.setSelectedIndex(0);
        co.viewTable("select * from bills_view",billsTableview);
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        
        String sql="SELECT bl.bil_no, pp.pepname as magacabilka, bl.bill_date, bl.Amounts as lacag, bl.description "
                + "FROM bills bl , people pp WHERE bl.people_no = pp.people_no and bl.bil_no='"+txtserbill.getText()+"'";
        co.search(sql);
        try{
            if(co.rs.next()){
                idbil=co.rs.getString("bil_no");
                txtAmountBills.setText(co.rs.getString("lacag"));
                 txtdescriptionBills.setText(co.rs.getString("description"));
                jDateBillDates.setDate(co.rs.getDate("bill_date"));
                billspeople_no.setSelectedItem(co.rs.getString("magacabilka"));
                btnSave.setEnabled(false);
                txtserbill.setText("");
            }
            else
            JOptionPane.showMessageDialog(null, "Xogtaan Lama Helin");
            txtserbill.setText("");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());

        }
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> billspeople_no;
    private javax.swing.JLabel btnSave;
    private necesario.LabelIcon btnclose;
    private app.bolivia.swing.JCTextField jCTextField1;
    private app.bolivia.swing.JCTextField jCTextField2;
    private app.bolivia.swing.JCTextField jCTextField3;
    private com.toedter.calendar.JDateChooser jDateBillDates;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private app.bolivia.swing.JCTextField txtAmountBills;
    private app.bolivia.swing.JCTextField txtdescriptionBills;
    private app.bolivia.swing.JCTextField txtserbill;
    // End of variables declaration//GEN-END:variables
}
