/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team_management;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ALka Media
 */
public class Dashboard1 extends javax.swing.JFrame {

    Codes co=new Codes();
    
    public void display(){
        co.viewTable("select * from jobs", tableMetro1);
       // co.viewTable("select * from people", peptabale);
}    String pubid="";
     String id="";
     String oper="";
             
    public Dashboard1() {
        initComponents();
        display();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        btnpa = new javax.swing.JLabel();
        btnacc = new RSMaterialComponent.RSLabelTextIcon();
        btnpy = new RSMaterialComponent.RSLabelTextIcon();
        btnbil = new RSMaterialComponent.RSLabelTextIcon();
        btncom = new javax.swing.JLabel();
        btnteam = new javax.swing.JLabel();
        btnact = new javax.swing.JLabel();
        btnma = new javax.swing.JLabel();
        btnmatches = new RSMaterialComponent.RSLabelTextIcon();
        btnpep = new RSMaterialComponent.RSLabelTextIcon();
        btnjob = new RSMaterialComponent.RSLabelTextIcon();
        rSLabelTextIcon2 = new RSMaterialComponent.RSLabelTextIcon();
        jPanel3 = new javax.swing.JPanel();
        rSButtonIcon_new6 = new newscomponents.RSButtonIcon_new();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        btnsave = new newscomponents.RSButtonIcon_new();
        rSButtonIcon_new3 = new newscomponents.RSButtonIcon_new();
        rSButtonIcon_new4 = new newscomponents.RSButtonIcon_new();
        rSButtonIcon_new1 = new newscomponents.RSButtonIcon_new();
        txtser = new RSMaterialComponent.RSTextFieldIconOne();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMetro1 = new rojeru_san.complementos.TableMetro();
        jLabel3 = new javax.swing.JLabel();
        rSButtonGradiente1 = new rsbuttongradiente.RSButtonGradiente();
        txtval = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        rSButtonIcon_new5 = new newscomponents.RSButtonIcon_new();
        rSTextFieldIconOne1 = new RSMaterialComponent.RSTextFieldIconOne();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 10, new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelTextIcon1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, null));
        rSLabelTextIcon1.setForeground(new java.awt.Color(255, 204, 204));
        rSLabelTextIcon1.setText("Dashboard");
        rSLabelTextIcon1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DASHBOARD);
        jPanel2.add(rSLabelTextIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, -1));

        btnpa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnpa.setForeground(new java.awt.Color(255, 255, 255));
        btnpa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/pleyer.png"))); // NOI18N
        btnpa.setText("       Player Agriments");
        btnpa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.white, null, null));
        btnpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpaMouseExited(evt);
            }
        });
        jPanel2.add(btnpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 200, 40));

        btnacc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.lightGray, null, null));
        btnacc.setForeground(new java.awt.Color(255, 255, 255));
        btnacc.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnacc.setText("       Accounts");
        btnacc.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_BALANCE);
        btnacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnaccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnaccMouseExited(evt);
            }
        });
        jPanel2.add(btnacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 200, 40));

        btnpy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.lightGray, null, null));
        btnpy.setForeground(new java.awt.Color(255, 255, 255));
        btnpy.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnpy.setText("       Payments");
        btnpy.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PAYMENT);
        btnpy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpyMouseExited(evt);
            }
        });
        jPanel2.add(btnpy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 200, 40));

        btnbil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.lightGray, null, null));
        btnbil.setForeground(new java.awt.Color(255, 255, 255));
        btnbil.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnbil.setText("       Bills");
        btnbil.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MONETIZATION_ON);
        btnbil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbilMouseExited(evt);
            }
        });
        jPanel2.add(btnbil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 200, 40));

        btncom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btncom.setForeground(new java.awt.Color(255, 255, 255));
        btncom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/teams4.png"))); // NOI18N
        btncom.setText("       Competitions");
        btncom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.white, null, null));
        btncom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncomMouseExited(evt);
            }
        });
        jPanel2.add(btncom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 200, 40));

        btnteam.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnteam.setForeground(new java.awt.Color(255, 255, 255));
        btnteam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/READY12.png"))); // NOI18N
        btnteam.setText("        Teams");
        btnteam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.white, null, null));
        btnteam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnteamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnteamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnteamMouseExited(evt);
            }
        });
        jPanel2.add(btnteam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 200, 40));

        btnact.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnact.setForeground(new java.awt.Color(255, 255, 255));
        btnact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/m actv.png"))); // NOI18N
        btnact.setText("   Activity");
        btnact.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.white, null, null));
        btnact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnactMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnactMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnactMouseExited(evt);
            }
        });
        jPanel2.add(btnact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 200, 40));

        btnma.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnma.setForeground(new java.awt.Color(255, 255, 255));
        btnma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/READY9.png"))); // NOI18N
        btnma.setText("      Match_activity");
        btnma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.white, null, null));
        btnma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmaMouseExited(evt);
            }
        });
        jPanel2.add(btnma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, 40));

        btnmatches.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.lightGray, null, null));
        btnmatches.setForeground(new java.awt.Color(255, 255, 255));
        btnmatches.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnmatches.setText("        Matches");
        btnmatches.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.GAMEPAD);
        btnmatches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmatchesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmatchesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmatchesMouseExited(evt);
            }
        });
        jPanel2.add(btnmatches, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 200, 40));

        btnpep.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.lightGray, null, null));
        btnpep.setForeground(new java.awt.Color(255, 255, 255));
        btnpep.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnpep.setText("        people");
        btnpep.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PEOPLE);
        btnpep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpepMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpepMouseExited(evt);
            }
        });
        jPanel2.add(btnpep, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 200, 40));

        btnjob.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.lightGray, null, null));
        btnjob.setForeground(new java.awt.Color(255, 255, 255));
        btnjob.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnjob.setText("       Jobs ");
        btnjob.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.WORK);
        btnjob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnjobMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnjobMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnjobMouseExited(evt);
            }
        });
        jPanel2.add(btnjob, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 200, 40));

        rSLabelTextIcon2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, null));
        rSLabelTextIcon2.setForeground(new java.awt.Color(255, 204, 204));
        rSLabelTextIcon2.setText("Dashboard");
        rSLabelTextIcon2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        rSLabelTextIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DASHBOARD);
        jPanel2.add(rSLabelTextIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 720));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 10, 0, new java.awt.Color(204, 204, 204)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonIcon_new6.setBackground(new java.awt.Color(0, 102, 102));
        rSButtonIcon_new6.setText("PEOPLE");
        rSButtonIcon_new6.setBackgroundHover(new java.awt.Color(0, 153, 153));
        rSButtonIcon_new6.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSButtonIcon_new6.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        rSButtonIcon_new6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonIcon_new6MouseClicked(evt);
            }
        });
        rSButtonIcon_new6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIcon_new6ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonIcon_new6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1120, 170));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Job_Name");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 40));

        txt1.setBackground(new java.awt.Color(153, 153, 153));
        txt1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txt1.setCaretColor(new java.awt.Color(255, 255, 255));
        txt1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt1InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt1KeyPressed(evt);
            }
        });
        jPanel4.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 220, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Description");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 40));

        txt2.setBackground(new java.awt.Color(153, 153, 153));
        txt2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        txt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txt2.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel4.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 220, 40));

        btnsave.setBackground(new java.awt.Color(153, 153, 153));
        btnsave.setText("Save");
        btnsave.setBackgroundHover(new java.awt.Color(0, 153, 153));
        btnsave.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        btnsave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnsaveKeyPressed(evt);
            }
        });
        jPanel4.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 90, 40));

        rSButtonIcon_new3.setBackground(new java.awt.Color(153, 153, 153));
        rSButtonIcon_new3.setText("Update");
        rSButtonIcon_new3.setBackgroundHover(new java.awt.Color(0, 153, 153));
        rSButtonIcon_new3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        rSButtonIcon_new3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIcon_new3ActionPerformed(evt);
            }
        });
        jPanel4.add(rSButtonIcon_new3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 100, 40));

        rSButtonIcon_new4.setBackground(new java.awt.Color(153, 153, 153));
        rSButtonIcon_new4.setText("Reset");
        rSButtonIcon_new4.setToolTipText("");
        rSButtonIcon_new4.setBackgroundHover(new java.awt.Color(0, 153, 153));
        rSButtonIcon_new4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR);
        rSButtonIcon_new4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIcon_new4ActionPerformed(evt);
            }
        });
        jPanel4.add(rSButtonIcon_new4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 90, 40));

        rSButtonIcon_new1.setBackground(new java.awt.Color(153, 153, 153));
        rSButtonIcon_new1.setText("Delete");
        rSButtonIcon_new1.setActionCommand("Save");
        rSButtonIcon_new1.setBackgroundHover(new java.awt.Color(0, 153, 153));
        rSButtonIcon_new1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        rSButtonIcon_new1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIcon_new1ActionPerformed(evt);
            }
        });
        jPanel4.add(rSButtonIcon_new1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 100, 40));

        txtser.setForeground(new java.awt.Color(0, 0, 0));
        txtser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtser.setColorIcon(new java.awt.Color(0, 102, 102));
        txtser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtser.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtser.setPhColor(new java.awt.Color(0, 102, 102));
        txtser.setPlaceholder("Type Here To Search");
        txtser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserActionPerformed(evt);
            }
        });
        jPanel4.add(txtser, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, -1));

        tableMetro1.setForeground(new java.awt.Color(0, 153, 153));
        tableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "JOB_NO", "JOB_NAME", "DESCRIPTION"
            }
        ));
        tableMetro1.setColorBackgoundHead(new java.awt.Color(0, 204, 204));
        jScrollPane1.setViewportView(tableMetro1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 630, 350));

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/job4.png"))); // NOI18N
        jLabel3.setOpaque(true);
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 130));

        rSButtonGradiente1.setBackground(new java.awt.Color(0, 204, 204));
        rSButtonGradiente1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, null));
        rSButtonGradiente1.setText("Search");
        rSButtonGradiente1.setColorPrimario(new java.awt.Color(0, 204, 204));
        rSButtonGradiente1.setColorPrimarioHover(new java.awt.Color(204, 0, 204));
        rSButtonGradiente1.setColorSecundario(new java.awt.Color(255, 0, 153));
        rSButtonGradiente1.setColorSecundarioHover(new java.awt.Color(0, 255, 204));
        rSButtonGradiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradiente1ActionPerformed(evt);
            }
        });
        jPanel4.add(rSButtonGradiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, 90, 40));

        txtval.setBackground(new java.awt.Color(0, 153, 153));
        txtval.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtval.setForeground(new java.awt.Color(255, 255, 255));
        txtval.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtvalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtvalMousePressed(evt);
            }
        });
        txtval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtvalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvalKeyTyped(evt);
            }
        });
        jPanel4.add(txtval, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 220, 30));

        jTabbedPane1.addTab("Jobs", jPanel4);

        jPanel5.setBackground(new java.awt.Color(51, 51, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonIcon_new5.setBackground(new java.awt.Color(0, 102, 102));
        rSButtonIcon_new5.setText("Add New Record");
        rSButtonIcon_new5.setBackgroundHover(new java.awt.Color(0, 153, 153));
        rSButtonIcon_new5.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSButtonIcon_new5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        rSButtonIcon_new5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonIcon_new5MouseClicked(evt);
            }
        });
        rSButtonIcon_new5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIcon_new5ActionPerformed(evt);
            }
        });
        jPanel5.add(rSButtonIcon_new5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        rSTextFieldIconOne1.setBackground(new java.awt.Color(0, 153, 153));
        rSTextFieldIconOne1.setForeground(new java.awt.Color(0, 0, 0));
        rSTextFieldIconOne1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rSTextFieldIconOne1.setBorderColor(new java.awt.Color(255, 255, 255));
        rSTextFieldIconOne1.setColorIcon(new java.awt.Color(255, 255, 255));
        rSTextFieldIconOne1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSTextFieldIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSTextFieldIconOne1.setPhColor(new java.awt.Color(204, 204, 204));
        rSTextFieldIconOne1.setPlaceholder("Type Here To Search");
        rSTextFieldIconOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldIconOne1ActionPerformed(evt);
            }
        });
        jPanel5.add(rSTextFieldIconOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, 40));

        jLabel4.setBackground(new java.awt.Color(255, 204, 0));
        jLabel4.setOpaque(true);
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 80));

        jPanel17.setBackground(new java.awt.Color(51, 102, 0));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane2.addTab("tab1", jPanel17);

        jPanel18.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1105, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab2", jPanel18);

        jPanel5.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1110, 480));

        jTabbedPane1.addTab("People", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab6", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab7", jPanel10);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab8", jPanel11);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab9", jPanel12);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab10", jPanel13);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab11", jPanel14);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab12", jPanel15);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab13", jPanel16);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 1120, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpaMouseClicked
        // TODO add your handling code here:
               jTabbedPane1.setSelectedIndex(10);

        //        this.hide();
        //        pa.show();
    }//GEN-LAST:event_btnpaMouseClicked

    private void btnpaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpaMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,204,204);
        btnpa.setBackground(clr);
    }//GEN-LAST:event_btnpaMouseEntered

    private void btnpaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpaMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        btnpa.setBackground(clr);
    }//GEN-LAST:event_btnpaMouseExited

    private void btnaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaccMouseClicked
        // TODO add your handling code here:

                jTabbedPane1.setSelectedIndex(9);

        //        this.hide();
        //        acc.show();
    }//GEN-LAST:event_btnaccMouseClicked

    private void btnaccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaccMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        btnacc.setBackground(clr);
    }//GEN-LAST:event_btnaccMouseEntered

    private void btnaccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaccMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,204,204);
        btnacc.setBackground(clr);
    }//GEN-LAST:event_btnaccMouseExited

    private void btnpyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpyMouseClicked
        // TODO add your handling code here:
               jTabbedPane1.setSelectedIndex(8);

        //        this.hide();
        //        py.show();
    }//GEN-LAST:event_btnpyMouseClicked

    private void btnpyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpyMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,204,204);
        btnpy.setBackground(clr);

    }//GEN-LAST:event_btnpyMouseEntered

    private void btnpyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpyMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        btnpy.setBackground(clr);
    }//GEN-LAST:event_btnpyMouseExited

    private void btnbilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbilMouseClicked
        // TODO add your handling code here:
               jTabbedPane1.setSelectedIndex(7);

        //this.hide();
        //bf.show();
    }//GEN-LAST:event_btnbilMouseClicked

    private void btnbilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbilMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,204,204);
        btnbil.setBackground(clr);
    }//GEN-LAST:event_btnbilMouseEntered

    private void btnbilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbilMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        btnbil.setBackground(clr);
    }//GEN-LAST:event_btnbilMouseExited

    private void btncomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncomMouseClicked
        // TODO add your handling code here:

               jTabbedPane1.setSelectedIndex(6);

        //        this.hide();
        //        co.show();

    }//GEN-LAST:event_btncomMouseClicked

    private void btncomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncomMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,204,204);
        btncom.setBackground(clr);
    }//GEN-LAST:event_btncomMouseEntered

    private void btncomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncomMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        btncom.setBackground(clr);
    }//GEN-LAST:event_btncomMouseExited

    private void btnteamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnteamMouseClicked
        // TODO add your handling code here:
                jTabbedPane1.setSelectedIndex(5);

        //this.hide();

    }//GEN-LAST:event_btnteamMouseClicked

    private void btnteamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnteamMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        btnteam.setBackground(clr);
    }//GEN-LAST:event_btnteamMouseEntered

    private void btnteamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnteamMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,204,204);
        btnteam.setBackground(clr);
    }//GEN-LAST:event_btnteamMouseExited

    private void btnactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnactMouseClicked
        // TODO add your handling code here:
                jTabbedPane1.setSelectedIndex(4);


        //ac.show();
    }//GEN-LAST:event_btnactMouseClicked

    private void btnactMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnactMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,204,204);
        btnact.setBackground(clr);
    }//GEN-LAST:event_btnactMouseEntered

    private void btnactMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnactMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        btnact.setBackground(clr);
    }//GEN-LAST:event_btnactMouseExited

    private void btnmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmaMouseClicked
        // TODO add your handling code here:
               jTabbedPane1.setSelectedIndex(3);

        //        this.hide();
        //        ma.show();
    }//GEN-LAST:event_btnmaMouseClicked

    private void btnmaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmaMouseEntered
        // TODO add your handling code here
        Color clr = new Color(0,204,204);
        btnma.setBackground(clr);
    }//GEN-LAST:event_btnmaMouseEntered

    private void btnmaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmaMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        btnma.setBackground(clr);
    }//GEN-LAST:event_btnmaMouseExited

    private void btnmatchesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmatchesMouseClicked
        // TODO add your handling code here:

               jTabbedPane1.setSelectedIndex(2);

        //this.hide();
        //mc.show();
    }//GEN-LAST:event_btnmatchesMouseClicked

    private void btnmatchesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmatchesMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,204,204);
        btnmatches.setBackground(clr);
    }//GEN-LAST:event_btnmatchesMouseEntered

    private void btnmatchesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmatchesMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        btnmatches.setBackground(clr);
    }//GEN-LAST:event_btnmatchesMouseExited

    private void btnpepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpepMouseClicked
        // TODO add your handling code here:
                jTabbedPane1.setSelectedIndex(1);
                
                
                

        //this.hide();
        //tm.show();
    }//GEN-LAST:event_btnpepMouseClicked

    private void btnpepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpepMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,204,204);
        btnpep.setBackground(clr);
    }//GEN-LAST:event_btnpepMouseEntered

    private void btnpepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpepMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        btnpep.setBackground(clr);
    }//GEN-LAST:event_btnpepMouseExited

    private void btnjobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjobMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        //this.hide();
        //jt.show();
    }//GEN-LAST:event_btnjobMouseClicked

    private void btnjobMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjobMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,204,204);
        btnjob.setBackground(clr);
    }//GEN-LAST:event_btnjobMouseEntered

    private void btnjobMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjobMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        btnjob.setBackground(clr);
    }//GEN-LAST:event_btnjobMouseExited

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String oper="insert";
        String sql="call jobs_proc(null,'"+txt1.getText()+"', '"+txt2.getText()+"','"+oper+"')";
        co.setSQL(sql);
        display();
        txt1.setText(""); 
        txt2.setText("");

    }//GEN-LAST:event_btnsaveActionPerformed

    private void rSButtonIcon_new3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIcon_new3ActionPerformed
        // TODO add your handling code here:
        String oper="update";
        String sql="call jobs_proc('"+id+"','"+txt1.getText()+"', '"+txt2.getText()+"','"+oper+"')";
        co.setSQL(sql);
        display();
        txt1.setText("");  txt2.setText("");
        btnsave.setEnabled(true);

    }//GEN-LAST:event_rSButtonIcon_new3ActionPerformed

    private void rSButtonIcon_new4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIcon_new4ActionPerformed
        // TODO add your handling code here:

        txt1.setText("");
        txt2.setText("");
        btnsave.setEnabled(true);
    }//GEN-LAST:event_rSButtonIcon_new4ActionPerformed

    private void rSButtonIcon_new1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIcon_new1ActionPerformed
        // TODO add your handling code here:
        // delete part..............................
        String oper="delete";
        String sql="call jobs_proc('"+id+"','"+txt1.getText()+"', '"+txt2.getText()+"','"+oper+"')";
        if(JOptionPane.showConfirmDialog(null, "ma hubtaa","xaqiijin",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
        co.setSQL(sql);
        display();
        txt1.setText("");  txt2.setText("");
        btnsave.setEnabled(true);

    }//GEN-LAST:event_rSButtonIcon_new1ActionPerformed
    }
    private void txtserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserActionPerformed

    private void rSButtonGradiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente1ActionPerformed
        // TODO add your handling code here:
        // search part..............................................
        String sql="select * from jobs where name='"+txtser.getText()+"' or Description='"+txtser.getText()+"' or job_no='"+txtser.getText()+"'";
        co.search(sql);
        try{
            if(co.rs.next()){
                id=co.rs.getString("JOB_NO");
                txt1.setText(co.rs.getString("name"));
                txt2.setText(co.rs.getString("Description"));
                btnsave.setEnabled(false);
                txtser.setText("");
            }
            else
            JOptionPane.showMessageDialog(null, "Xogtaan Lama Helin");
            txtser.setText("");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_rSButtonGradiente1ActionPerformed

    private void txt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyPressed
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(Character.isLetter(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch))
        {
            txt1.setEditable(true);
            txtval.setText("");
        }
        else
        {
            txt1.setEditable(false);
            txtval.setText("please fill the Name ?");
        }
        
        
    }//GEN-LAST:event_txt1KeyPressed

    private void btnsaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnsaveKeyPressed
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(Character.isLetter(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch))
        {
            txt1.setEditable(true);
            txtval.setText("");
        }
        else
        {
            txt1.setEditable(false);
            txtval.setText("please fill the Name ?");
        }
    }//GEN-LAST:event_btnsaveKeyPressed

    private void txtvalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalKeyPressed
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(Character.isLetter(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch))
        {
            txt1.setEditable(true);
            txtval.setText("");
        }
        else
        {
            txt1.setEditable(false);
            txtval.setText("please fill the Name ?");
        }
    }//GEN-LAST:event_txtvalKeyPressed

    private void txtvalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtvalMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtvalMouseClicked

    private void txt1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1InputMethodTextChanged

    private void txtvalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtvalMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtvalMousePressed

    private void txtvalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(Character.isLetter(ch) || Character.isWhitespace(ch) || Character.isISOControl(ch) ||Character.isSpaceChar(ch))
        {
            txt1.setEditable(true);
            txtval.setText("");
        }
        else
        {
            txt1.setEditable(false);
            txtval.setText("please fill the Name ?");
        }
    }//GEN-LAST:event_txtvalKeyTyped

    private void rSButtonIcon_new5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIcon_new5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(1);
       
    }//GEN-LAST:event_rSButtonIcon_new5ActionPerformed

    private void rSButtonIcon_new5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonIcon_new5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIcon_new5MouseClicked

    private void rSTextFieldIconOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldIconOne1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldIconOne1ActionPerformed

    private void rSButtonIcon_new6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonIcon_new6MouseClicked
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(1);
        
    }//GEN-LAST:event_rSButtonIcon_new6MouseClicked

    private void rSButtonIcon_new6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIcon_new6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIcon_new6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSLabelTextIcon btnacc;
    private javax.swing.JLabel btnact;
    private RSMaterialComponent.RSLabelTextIcon btnbil;
    private javax.swing.JLabel btncom;
    private RSMaterialComponent.RSLabelTextIcon btnjob;
    private javax.swing.JLabel btnma;
    private RSMaterialComponent.RSLabelTextIcon btnmatches;
    private javax.swing.JLabel btnpa;
    private RSMaterialComponent.RSLabelTextIcon btnpep;
    private RSMaterialComponent.RSLabelTextIcon btnpy;
    private newscomponents.RSButtonIcon_new btnsave;
    private javax.swing.JLabel btnteam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradiente1;
    private newscomponents.RSButtonIcon_new rSButtonIcon_new1;
    private newscomponents.RSButtonIcon_new rSButtonIcon_new3;
    private newscomponents.RSButtonIcon_new rSButtonIcon_new4;
    private newscomponents.RSButtonIcon_new rSButtonIcon_new5;
    private newscomponents.RSButtonIcon_new rSButtonIcon_new6;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon2;
    private RSMaterialComponent.RSTextFieldIconOne rSTextFieldIconOne1;
    private rojeru_san.complementos.TableMetro tableMetro1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private RSMaterialComponent.RSTextFieldIconOne txtser;
    private javax.swing.JLabel txtval;
    // End of variables declaration//GEN-END:variables

    private static class jTabbedPane2 {

        public jTabbedPane2() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private void toFront() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

    private static class jTabbedPane1 {

        public jTabbedPane1() {
        }

        private void toFront() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private void setState(int NORMAL) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
