/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team_management;

import javax.swing.JOptionPane;
import static sun.security.jgss.GSSUtil.login;

/**
 *
 * @author MohameD
 */
public class Forgot extends javax.swing.JFrame {
Codes co = new Codes();
    /**
     * Creates new form Forgot
     */
    public Forgot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtemail = new rscomponentshade.RSTextFieldShade();
        txtname = new rscomponentshade.RSTextFieldShade();
        jLabel4 = new javax.swing.JLabel();
        showpass = new javax.swing.JLabel();
        usershow = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtemail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtemail.setPlaceholder("Enter Email");
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 220, 50));

        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtname.setPlaceholder("Enter Name");
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 220, 50));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Forgot password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 370, 70));

        showpass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        showpass.setForeground(new java.awt.Color(255, 255, 255));
        showpass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(showpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 180, 30));

        usershow.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        usershow.setForeground(new java.awt.Color(255, 255, 255));
        usershow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(usershow, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 180, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (48).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 120, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (47).png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 130, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (44).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (45).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 110, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/forgot.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 410, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        
        String sql="select user,password as pass from users where name='"+txtname.getText()+"' and Email='"+txtemail.getText()+"'";
        co.search(sql);
        try {
              if(co.rs.next()){
            usershow.setText(co.rs.getString("user"));
            showpass.setText(co.rs.getString("pass"));
        }
              else
                  JOptionPane.showMessageDialog(null,"Invalid result");
        } catch (Exception e) {
        }
        
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Login ln = new Login();
        ln.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel showpass;
    private rscomponentshade.RSTextFieldShade txtemail;
    private rscomponentshade.RSTextFieldShade txtname;
    private javax.swing.JLabel usershow;
    // End of variables declaration//GEN-END:variables
}
