/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team_management;

import java.awt.Color;
import javax.swing.JOptionPane;
import static team_management.dashboard.Jobtable;

/**
 *
 * @author ALka Media
 */
public class jobs extends javax.swing.JFrame {
    
    Codes co=new Codes();
    public void display(){
}    String pubid="";
     String idjo="";
     String oper="";
             
     //DefaultTablemodel d;

    /**
     * Creates new form jobs
     */
    public jobs() {
        initComponents();
        display();
        
    }
    public boolean validation()
    {
        if(txtjobName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Name");
            return false;
        }
        return true;
    }
    
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelImageBeanInfo1 = new rojerusan.RSPanelImageBeanInfo();
        swingTimerTimingSource1 = new org.jdesktop.swing.animation.timing.sources.SwingTimerTimingSource();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtserJOBS = new RSMaterialComponent.RSTextFieldTwo();
        btnclose = new necesario.LabelIcon();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnsave = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        showjobname = new javax.swing.JLabel();
        showjobdesc = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (26).png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 100, 40));

        txtserJOBS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtserJOBS.setPlaceholder("Type Here To Search");
        jPanel2.add(txtserJOBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, 40));

        btnclose.setBackground(new java.awt.Color(0, 102, 102));
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR);
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncloseMouseExited(evt);
            }
        });
        jPanel2.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("+ Add Job");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 270, 60));

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.orange, java.awt.Color.lightGray));
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 100));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("JobName");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Description");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 40));

        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (21).png"))); // NOI18N
        btnsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsaveMouseClicked(evt);
            }
        });
        jPanel2.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 90, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (22).png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 110, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (25).png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 100, 40));

        txtjobDescription.setForeground(new java.awt.Color(0, 0, 0));
        txtjobDescription.setBorderColor(new java.awt.Color(0, 102, 102));
        txtjobDescription.setPlaceholder("JobDescription");
        txtjobDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtjobDescriptionKeyPressed(evt);
            }
        });
        jPanel2.add(txtjobDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 200, -1));

        txtjobName.setForeground(new java.awt.Color(0, 0, 0));
        txtjobName.setBorderColor(new java.awt.Color(0, 102, 102));
        txtjobName.setPlaceholder("JobName");
        txtjobName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtjobNameKeyPressed(evt);
            }
        });
        jPanel2.add(txtjobName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 200, -1));

        showjobname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        showjobname.setForeground(new java.awt.Color(255, 255, 255));
        showjobname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(showjobname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 200, 30));

        showjobdesc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        showjobdesc.setForeground(new java.awt.Color(255, 255, 255));
        showjobdesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(showjobdesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 200, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/jobimage2.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 450, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     
    
    
    
    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
         // TODO add your handling code here:
         this.hide();
    }//GEN-LAST:event_btncloseMouseClicked

    private void btncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        btnclose.setBackground(clr);
    }//GEN-LAST:event_btncloseMouseEntered

    private void btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        btnclose.setBackground(clr);
    }//GEN-LAST:event_btncloseMouseExited

    private void btnsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseClicked
        // TODO add your handling code here:
        String oper="insert";
        String sql="call job_proc(null,'"+txtjobName.getText()+"', '"+txtjobDescription.getText()+"','"+oper+"')";
        co.setSQL(sql);
        display();
        txtjobName.setText("");  txtjobDescription.setText("");
        co.viewTable("select * from jobs_view",Jobtable);
        
    }//GEN-LAST:event_btnsaveMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
         String oper="update";
        String sql="call job_proc('"+idjo+"','"+txtjobName.getText()+"', '"+txtjobDescription.getText()+"','"+oper+"')";
        co.setSQL(sql);
        display();
      txtjobName.setText("");  txtjobDescription.setText("");
      co.viewTable("select * from jobs_view",Jobtable);
      btnsave.setEnabled(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        
        if(JOptionPane.showConfirmDialog(null, "ma hubtaa","xaqiijin",
                     JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
        String oper="delete";
        String sql="call job_proc('"+idjo+"','"+txtjobName.getText()+"', '"+txtjobDescription.getText()+"','"+oper+"')";
      co.setSQL(sql);
      display();
      txtjobName.setText("");  txtjobName.setText(""); 
      co.viewTable("select * from jobs_view",Jobtable);
      btnsave.setEnabled(true);
        
    }//GEN-LAST:event_jLabel7MouseClicked
    }
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
         // TODO add your handling code here:
        String sql="select * from jobs where jobname='"+txtserJOBS.getText()+"' or job_no='"+txtserJOBS.getText()+"'";
        co.search(sql);
        try{
            if(co.rs.next()){
                idjo=co.rs.getString("job_no");
                txtjobName.setText(co.rs.getString("jobname"));
                txtjobDescription.setText(co.rs.getString("description"));
                btnsave.setEnabled(false);
                txtserJOBS.setText("");
            }
            else
            JOptionPane.showMessageDialog(null, "Xogtaan Lama Helin");
            txtserJOBS.setText("");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void txtjobNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjobNameKeyPressed
         // TODO add your handling code here:
         char c= evt.getKeyChar();
        if(Character.isLetter(c)|| Character.isWhitespace(c)|| Character.isISOControl(c)){
            txtjobName.setEditable(true);
            showjobname.setText("");
        }
        else
        {
            txtjobName.setEditable(false);
            showjobname.setText("Only Letters Are Allowed");
        }
    }//GEN-LAST:event_txtjobNameKeyPressed

    private void txtjobDescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjobDescriptionKeyPressed
        // TODO add your handling code here:
        
        char c= evt.getKeyChar();
        if(Character.isLetter(c)|| Character.isWhitespace(c)|| Character.isISOControl(c)){
            txtjobDescription.setEditable(true);
            showjobdesc.setText("");
        }
        else
        {
            txtjobDescription.setEditable(false);
            showjobdesc.setText("Only Letters Are Allowed");
        }
        
    }//GEN-LAST:event_txtjobDescriptionKeyPressed
    
    
    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jobs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private necesario.LabelIcon btnclose;
    private javax.swing.JLabel btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSPanelImageBeanInfo rSPanelImageBeanInfo1;
    private javax.swing.JLabel showjobdesc;
    private javax.swing.JLabel showjobname;
    private org.jdesktop.swing.animation.timing.sources.SwingTimerTimingSource swingTimerTimingSource1;
    public static final RSMaterialComponent.RSTextFieldTwo txtjobDescription = new RSMaterialComponent.RSTextFieldTwo();
    public static final RSMaterialComponent.RSTextFieldTwo txtjobName = new RSMaterialComponent.RSTextFieldTwo();
    private RSMaterialComponent.RSTextFieldTwo txtserJOBS;
    // End of variables declaration//GEN-END:variables
}
