/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team_management;

import java.awt.Color;
import javax.swing.JOptionPane;
import static team_management.dashboard.matcAccTable;

/**
 *
 * @author ALka Media
 */
public class match_activity extends javax.swing.JFrame {

    Codes co = new Codes();

    public void display() {
    }
    String idmac = "";
    String activity = "";
    String match = "";
    String mpeople = "";
    String oper = "";
    String com1="";
    String com2="";

    /**
     * Creates new form match_activity
     */
    public match_activity() {
        initComponents();
        
        co.fillCombo("SELECT activityName as  'activity_Name' FROM activites", activity_no, "activity_Name");
        co.fillCombo("SELECT teamsName as  'Team_Name' FROM teams", match_no, "Team_Name");
        co.fillCombo("SELECT pepname as  'Names' FROM people", people_no, "Names");
        //co.fillCombo("SELECT mat_date as  'DateTime' FROM matches",act_time,"DateTime");
       display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnclose = new necesario.LabelIcon();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        activity_no = new javax.swing.JComboBox<>();
        people_no = new javax.swing.JComboBox<>();
        match_no = new javax.swing.JComboBox<>();
        txtmatchAct = new javax.swing.JTextField();
        txtmatchactdes = new javax.swing.JTextField();
        btnSave = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmatchactser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnclose.setBackground(new java.awt.Color(0, 153, 153));
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR);
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncloseMouseExited(evt);
            }
        });
        jPanel2.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/READY6.png"))); // NOI18N
        jLabel1.setText("Match_Activity");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 350, 80));

        jLabel6.setBackground(new java.awt.Color(0, 153, 153));
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 90));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("ActivityNo");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 110, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Description");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 110, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("TeamNO");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 100, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("peopleNo");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 110, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("ActiTime");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 100, 30));

        activity_no.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        activity_no.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Activity" }));
        activity_no.setSelectedItem(activity_no
        );
        activity_no.setToolTipText("");
        activity_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activity_noActionPerformed(evt);
            }
        });
        jPanel2.add(activity_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 260, 40));

        people_no.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        people_no.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "people_no" }));
        people_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                people_noActionPerformed(evt);
            }
        });
        jPanel2.add(people_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 260, 40));

        match_no.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        match_no.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Team_No" }));
        match_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                match_noActionPerformed(evt);
            }
        });
        jPanel2.add(match_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 260, 40));

        txtmatchAct.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtmatchAct.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtmatchAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatchActActionPerformed(evt);
            }
        });
        jPanel2.add(txtmatchAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 260, 40));

        txtmatchactdes.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtmatchactdes.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(txtmatchactdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 260, 40));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (21).png"))); // NOI18N
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 90, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (22).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 110, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (25).png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 100, 40));

        txtmatchactser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtmatchactser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtmatchactser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 190, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (26).png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/people1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 500, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
        // TODO add your handling code here:
        this.hide();

    }//GEN-LAST:event_btncloseMouseClicked

    private void btncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        btnclose.setBackground(clr);
    }//GEN-LAST:event_btncloseMouseEntered

    private void btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        btnclose.setBackground(clr);
    }//GEN-LAST:event_btncloseMouseExited

    private void activity_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activity_noActionPerformed
        // TODO add your handling code here:
        try {
            co.search("SELECT * FROM activites WHERE activityName='" + activity_no.getSelectedItem() + "'");
            if (co.rs.next()) {
                activity = co.rs.getString("act_no");
                match_no.setSelectedItem(com2);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_activity_noActionPerformed


    private void people_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_people_noActionPerformed
        // TODO add your handling code here:

        try {
            co.search("SELECT * FROM people WHERE pepname='" + people_no.getSelectedItem() + "'");
            if (co.rs.next()) {
                mpeople = co.rs.getString("people_no");
                
                
                

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }


    }//GEN-LAST:event_people_noActionPerformed

    private void match_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_match_noActionPerformed
        // TODO add your handling code here:

        try {
            co.search("SELECT * FROM teams WHERE teamsName='" + match_no.getSelectedItem() + "'");
            if (co.rs.next()) {
                match = co.rs.getString("team_no");
                people_no.setSelectedItem(com1);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }


    }//GEN-LAST:event_match_noActionPerformed

    private void txtmatchActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatchActActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatchActActionPerformed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
         String oper = "insert";
        String sql = "call MatchActivity_proc(null,'" + activity + "', '" + match + "','" + mpeople + "','" + txtmatchAct.getText() + "','" + txtmatchactdes.getText() + "','" + oper + "')";
//      co.setSQL(sql);
        display();
        co.setSQL(sql);
        co.viewTable("select * from match_activity_view",matcAccTable);

    }//GEN-LAST:event_btnSaveMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         String oper="update";
         String sql = "call MatchActivity_proc('"+idmac+"','" + activity + "', '" + match + "','" + mpeople + "','" + txtmatchAct.getText() + "','" + txtmatchactdes.getText() + "','" + oper + "')";
//      co.setSQL(sql);
        display();
        co.setSQL(sql);
        activity_no.setSelectedIndex(0);
        match_no.setSelectedIndex(0);
        people_no.setSelectedIndex(0);
        txtmatchactdes.setText(""); txtmatchAct.setText("");
        co.viewTable("select * from match_activity_view",matcAccTable);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "ma hubtaa","xaqiijin",
                     JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
        String oper="delete";
         String sql = "call MatchActivity_proc('"+idmac+"','" + activity + "', '" + match + "','" + mpeople + "','" + txtmatchAct.getText() + "','" + txtmatchactdes.getText() + "','" + oper + "')";
//      co.setSQL(sql);
        display();
        co.setSQL(sql);
        activity_no.setSelectedIndex(0);
        match_no.setSelectedIndex(0);
        people_no.setSelectedIndex(0);
        txtmatchactdes.setText(""); txtmatchAct.setText("");
        co.viewTable("select * from match_activity_view",matcAccTable);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
          // TODO add your handling code here:
         String sql = "SELECT m.mat_no, a.activityName as acmagac, t.teamsName as Kooxda, p.pepname as Qofka, m.mac_time as Saacada, "
                 + "m.description as Faahfaahin FROM match_activity m ,activites a ,matches ma , people p ,teams t where "
                 + "m.act_no=a.act_no and m.m_no=t.team_no and m.people_no=p.people_no and m.mat_no='" + txtmatchactser.getText() + "'";
        co.search(sql);
        try {
            if (co.rs.next()) {
                idmac = co.rs.getString("mat_no");

                txtmatchAct.setText(co.rs.getString("Saacada"));
                txtmatchactdes.setText(co.rs.getString("Faahfaahin"));
               
               
               com2=co.rs.getString("Kooxda");
               com1=co.rs.getString("Qofka");
               activity_no.setSelectedItem(co.rs.getString("acmagac"));
                btnSave.setEnabled(false);
                txtmatchactser.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Xogtaan Lama Helin");
            }
            txtmatchactser.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(match_activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(match_activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(match_activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(match_activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new match_activity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> activity_no;
    private javax.swing.JLabel btnSave;
    private necesario.LabelIcon btnclose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> match_no;
    private javax.swing.JComboBox<String> people_no;
    private javax.swing.JTextField txtmatchAct;
    private javax.swing.JTextField txtmatchactdes;
    private javax.swing.JTextField txtmatchactser;
    // End of variables declaration//GEN-END:variables
}
