/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team_management;

import java.awt.Color;
import java.sql.Date;
import javax.swing.JOptionPane;
import static team_management.dashboard.matchTables;

/**
 *
 * @author ALka Media
 */
public class matches extends javax.swing.JFrame {
    Codes co=new Codes();
     String idmatch="";
     String compe="";
     String mac5 ="";
     String teams="";
     String oper="";
    public void display(){
        
    }
  
    /**} } 
     * Creates new form matches
     */
    public matches() {
        initComponents();
        
       display();
       co.fillCombo("SELECT com_name as 'co' from competitions",macthescompe_no,"co");
       co.fillCombo("SELECT teamsName as 'team' from teams",matchesteam_no,"team");   
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnclose = new necesario.LabelIcon();
        txtsermatches = new RSMaterialComponent.RSTextFieldIconOne();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JDatematches = new com.toedter.calendar.JDateChooser();
        matchesteam_no = new javax.swing.JComboBox<>();
        macthescompe_no = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnclose.setBackground(new java.awt.Color(0, 102, 102));
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FORWARD);
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncloseMouseExited(evt);
            }
        });
        jPanel2.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 30, 30));

        txtsermatches.setForeground(new java.awt.Color(0, 0, 0));
        txtsermatches.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsermatches.setBorderColor(new java.awt.Color(255, 255, 255));
        txtsermatches.setColorIcon(new java.awt.Color(255, 255, 255));
        txtsermatches.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsermatches.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtsermatches.setPhColor(new java.awt.Color(204, 204, 204));
        txtsermatches.setPlaceholder("Type Here To Search");
        txtsermatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsermatchesActionPerformed(evt);
            }
        });
        jPanel2.add(txtsermatches, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 190, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/READY10.png"))); // NOI18N
        jLabel1.setText("   Matches");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, 90));

        jLabel6.setBackground(new java.awt.Color(0, 102, 102));
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("ComNo");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("TeamNo");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 100, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("MatDate");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 100, 30));

        JDatematches.setForeground(new java.awt.Color(0, 102, 102));
        JDatematches.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(JDatematches, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 260, 40));

        matchesteam_no.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select teams" }));
        matchesteam_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchesteam_noActionPerformed(evt);
            }
        });
        jPanel2.add(matchesteam_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 260, 40));

        macthescompe_no.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Competition" }));
        macthescompe_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                macthescompe_noActionPerformed(evt);
            }
        });
        jPanel2.add(macthescompe_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 260, 40));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (21).png"))); // NOI18N
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 90, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (22).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 110, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (25).png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 100, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (26).png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/jobimage2.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 440, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
        // TODO add your handling code here:
        
        this.hide();
      
    }//GEN-LAST:event_btncloseMouseClicked

    private void txtsermatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsermatchesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsermatchesActionPerformed

    private void btncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        btnclose.setBackground(clr);
    }//GEN-LAST:event_btncloseMouseEntered

    private void btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        btnclose.setBackground(clr);
    }//GEN-LAST:event_btncloseMouseExited

    private void macthescompe_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_macthescompe_noActionPerformed
        // TODO add your handling code here:
        try{
            co.search("SELECT * FROM competitions WHERE com_name='"+macthescompe_no.getSelectedItem()+"'");
            if(co.rs.next()){
               compe=co.rs.getString("com_no");
               matchesteam_no.setSelectedItem(mac5);
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_macthescompe_noActionPerformed

    private void matchesteam_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchesteam_noActionPerformed
        // TODO add your handling code here:
          try{
            co.search("SELECT * FROM teams WHERE teamsName='"+matchesteam_no.getSelectedItem()+"'");
            if(co.rs.next()){
               teams=co.rs.getString("team_no");
              // matchesteam_no.setSelectedItem(mac5);
               
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());}
    }//GEN-LAST:event_matchesteam_noActionPerformed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
        
        
        String oper="insert";
        Date dl=new Date(JDatematches.getDate().getTime());
        String sql="call matches_proc(null,'"+compe+"','"+teams+"','"+dl+"','"+oper+"')";
      co.setSQL(sql);
      display();
      co.viewTable("select * from matches_view",matchTables);
    }//GEN-LAST:event_btnSaveMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        String oper="update";
         Date dl=new Date(JDatematches.getDate().getTime());
        String sql = "call matches_proc('"+idmatch+"','"+compe+"','"+teams+"','"+dl+"','"+oper+"')";
        co.setSQL(sql);
        display();
        co.viewTable("select * from matches_view",matchTables);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
         String oper="delete";
         Date dl=new Date(JDatematches.getDate().getTime());
        String sql = "call matches_proc('"+idmatch+"','"+compe+"','"+teams+"','"+dl+"','"+oper+"')";
        co.setSQL(sql);
        display();
        co.viewTable("select * from matches_view",matchTables);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        String sql = "SELECT mch.m_no, com.com_name as tartanka, tm.teamsName as naadiga, mch.mat_date FROM "
                + "matches mch, teams tm, competitions com WHERE mch.com_no = com.com_no and "
                + "mch.team_no = tm.team_no and mch.m_no='"+txtsermatches.getText()+"'";
        co.search(sql);
        try {
            if (co.rs.next()) {
                idmatch = co.rs.getString("m_no");
               //com2=co.rs.getString("Team");
               mac5=co.rs.getString("naadiga");
               JDatematches.setDate(co.rs.getDate("mat_date"));
               macthescompe_no.setSelectedItem(co.rs.getString("tartanka"));
                btnSave.setEnabled(false);
                txtsermatches.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Xogtaan Lama Helin");
            }
            txtsermatches.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matches().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDatematches;
    private javax.swing.JLabel btnSave;
    private necesario.LabelIcon btnclose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> macthescompe_no;
    private javax.swing.JComboBox<String> matchesteam_no;
    private RSMaterialComponent.RSTextFieldIconOne txtsermatches;
    // End of variables declaration//GEN-END:variables
}
