/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team_management;

import java.awt.Color;
import java.sql.Date;
import javax.swing.JOptionPane;
import static team_management.dashboard.peopleTable;

/**
 *
 * @author ALka Media
 */
public class people extends javax.swing.JFrame {
     Codes co=new Codes();
      public void display(){
     co.fillCombo("SELECT jobname as  j FROM jobs",peoplejob_no,"j"); 
      }
      String idpep="";
     String pubid="";
     String name="";
     String tell="";
     String sex="";
     String weig="";
     String job="";
     String des="";
     String oper="";
     String Gender="";

    /**
     * Creates new form people
     */
    public people() {
        initComponents();
       
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        btnclose = new necesario.LabelIcon();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDatepeeoplereg = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtpeopleSer = new app.bolivia.swing.JCTextField();
        jLabel10 = new javax.swing.JLabel();
        txtdespeople = new app.bolivia.swing.JCTextField();
        jLabel11 = new javax.swing.JLabel();
        txtpeopleTell = new app.bolivia.swing.JCTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtweipeople = new app.bolivia.swing.JCTextField();
        jLabel14 = new javax.swing.JLabel();
        jDatepeople = new com.toedter.calendar.JDateChooser();
        peoplejob_no = new javax.swing.JComboBox<>();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        txtpeopleName = new app.bolivia.swing.JCTextField();
        btnsave = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        showmess = new javax.swing.JLabel();
        showtell = new javax.swing.JLabel();
        showdesc = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelTextIcon1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelTextIcon1.setText("registeration people");
        rSLabelTextIcon1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PEOPLE);
        jPanel2.add(rSLabelTextIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 540, 50));

        btnclose.setBackground(new java.awt.Color(0, 153, 153));
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR);
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncloseMouseExited(evt);
            }
        });
        jPanel2.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 30));

        jLabel6.setBackground(new java.awt.Color(0, 102, 102));
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Reg_Date");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 100, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("BrithDate");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 90, 40));
        jPanel2.add(jDatepeeoplereg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 240, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Name");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, 30));

        txtpeopleSer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtpeopleSer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpeopleSer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpeopleSer.setPhColor(new java.awt.Color(0, 102, 102));
        txtpeopleSer.setPlaceholder("Type Here To Search");
        txtpeopleSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpeopleSerActionPerformed(evt);
            }
        });
        jPanel2.add(txtpeopleSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, 140, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Desc");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 80, 30));

        txtdespeople.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtdespeople.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdespeople.setPhColor(new java.awt.Color(0, 102, 102));
        txtdespeople.setPlaceholder("Enter Desc");
        txtdespeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdespeopleActionPerformed(evt);
            }
        });
        txtdespeople.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdespeopleKeyPressed(evt);
            }
        });
        jPanel2.add(txtdespeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 240, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Tell");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 80, 30));

        txtpeopleTell.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtpeopleTell.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpeopleTell.setPhColor(new java.awt.Color(0, 102, 102));
        txtpeopleTell.setPlaceholder("Enter Tell");
        txtpeopleTell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpeopleTellActionPerformed(evt);
            }
        });
        txtpeopleTell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpeopleTellKeyPressed(evt);
            }
        });
        jPanel2.add(txtpeopleTell, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 240, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Sex");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 80, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("Weight");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 80, 30));

        txtweipeople.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtweipeople.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtweipeople.setPhColor(new java.awt.Color(0, 102, 102));
        txtweipeople.setPlaceholder("Enter Weight");
        txtweipeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtweipeopleActionPerformed(evt);
            }
        });
        jPanel2.add(txtweipeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 240, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("Job_no");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 80, 30));
        jPanel2.add(jDatepeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 240, 40));

        peoplejob_no.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Job" }));
        peoplejob_no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peoplejob_noMouseClicked(evt);
            }
        });
        peoplejob_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peoplejob_noActionPerformed(evt);
            }
        });
        jPanel2.add(peoplejob_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 240, 40));

        female.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup2.add(female);
        female.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel2.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 100, 30));

        male.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup2.add(male);
        male.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel2.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 100, 30));

        txtpeopleName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtpeopleName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpeopleName.setPhColor(new java.awt.Color(0, 102, 102));
        txtpeopleName.setPlaceholder("Enter Name");
        txtpeopleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpeopleNameActionPerformed(evt);
            }
        });
        txtpeopleName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpeopleNameKeyPressed(evt);
            }
        });
        jPanel2.add(txtpeopleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 240, 40));

        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (21).png"))); // NOI18N
        btnsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsaveMouseClicked(evt);
            }
        });
        jPanel2.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (22).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 630, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (25).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 630, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (26).png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 630, 100, 40));

        showmess.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        showmess.setForeground(new java.awt.Color(255, 255, 255));
        showmess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(showmess, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 190, 40));

        showtell.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        showtell.setForeground(new java.awt.Color(255, 255, 255));
        showtell.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showtell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                showtellKeyPressed(evt);
            }
        });
        jPanel2.add(showtell, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 180, 40));

        showdesc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        showdesc.setForeground(new java.awt.Color(255, 255, 255));
        showdesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(showdesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 180, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/people1.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 600, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtweipeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtweipeopleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtweipeopleActionPerformed

    private void txtpeopleTellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpeopleTellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpeopleTellActionPerformed

    private void txtdespeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdespeopleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdespeopleActionPerformed

    private void txtpeopleSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpeopleSerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpeopleSerActionPerformed

    private void btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        btnclose.setBackground(clr);
    }//GEN-LAST:event_btncloseMouseExited

    private void btncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        btnclose.setBackground(clr);
    }//GEN-LAST:event_btncloseMouseEntered

    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
         // TODO add your handling code here:
        this.hide();
        
    }//GEN-LAST:event_btncloseMouseClicked

    private void peoplejob_noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peoplejob_noMouseClicked
        // TODO add your handling code here:
        
//        try{ 
//          co.search("SELECT * FROM `jobs` WHERE name='"+job_no.getSelectedItem()+"'");
//         if(co.rs.next()){
//             job=co.rs.getString("job_no");
//             
//         }
//          }
//       catch(Exception ex){
//           JOptionPane.showMessageDialog(null, ex.getMessage());
//       }
    }//GEN-LAST:event_peoplejob_noMouseClicked

    private void peoplejob_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peoplejob_noActionPerformed
        // TODO add your handling code here:
        
        try{ 
          co.search("SELECT * FROM jobs WHERE jobname='"+peoplejob_no.getSelectedItem()+"'");
         if(co.rs.next()){
             job=co.rs.getString("job_no");
             
             
         }
          }
       catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex.getMessage());
       }
        
    }//GEN-LAST:event_peoplejob_noActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        Gender="Male";
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
        Gender="Female";
    }//GEN-LAST:event_femaleActionPerformed

    private void txtpeopleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpeopleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpeopleNameActionPerformed

    private void btnsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseClicked
        // TODO add your handling code here:
         String oper="insert";
        Date dl=new Date(jDatepeople.getDate().getTime());
        Date dl2=new Date(jDatepeeoplereg.getDate().getTime());
        String sql="call people_proc(null,'"+txtpeopleName.getText()+"', '"+txtpeopleTell.getText()+"',"
        + "'"+Gender+"','"+dl+"','"+txtweipeople.getText()+"',"
        + "'"+job+"','"+txtdespeople.getText()+"','"+dl2+"','"+oper+"')";
        co.setSQL(sql);
        display();
        txtpeopleName.setText("");
        txtpeopleTell.setText("");
        peoplejob_no.setSelectedIndex(0);
        txtweipeople.setText("");
        txtdespeople.setText("");
        co.viewTable("select * from people_view", peopleTable);
        
    }//GEN-LAST:event_btnsaveMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        String sql="SELECT p.people_no , p.pepname as Magaca ,p.tell ,p.sex as jinsi,p.birth_date , p.weight ,j.jobname as magacashaqada,"
                + "p.description ,p.reg_date FROM people  p , jobs j "
                + "WHERE p.job_no=j.job_no and people_no='"+txtpeopleSer.getText()+"'";
     co.search(sql);
     try{
         if(co.rs.next()){
             idpep=co.rs.getString("people_no");
             txtpeopleName.setText(co.rs.getString("Magaca"));
             txtpeopleTell.setText(co.rs.getString("tell"));
             Gender=co.rs.getString("jinsi");
             if(Gender.equals("Male"))
                 male.setSelected(true);
             else if(Gender.equals("Female"))
                 female.setSelected(true);
             jDatepeople.setDate(co.rs.getDate("birth_date"));
             txtweipeople.setText(co.rs.getString("weight"));
             txtdespeople.setText(co.rs.getString("description"));
             jDatepeeoplereg.setDate(co.rs.getDate("reg_date"));
             peoplejob_no.setSelectedItem(co.rs.getString("magacashaqada"));
             
             btnsave.setEnabled(false);
             txtpeopleSer.setText("");
         }
         else
             JOptionPane.showMessageDialog(null, "Xogtaan Lama Helin");
            txtpeopleSer.setText("");
     }catch(Exception ex){
         JOptionPane.showMessageDialog(null, ex.getMessage());
     }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "ma hubtaa","xaqiijin",
                     JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
         String oper="update";
        Date dl=new Date(jDatepeople.getDate().getTime());
        Date dl2=new Date(jDatepeeoplereg.getDate().getTime());
        String sql="call people_proc('"+idpep+"','"+txtpeopleName.getText()+"', '"+txtpeopleTell.getText()+"',"
        + "'"+Gender+"','"+dl+"','"+txtweipeople.getText()+"',"
        + "'"+job+"','"+txtdespeople.getText()+"','"+dl2+"','"+oper+"')";
        co.setSQL(sql);
        display();
        txtpeopleName.setText("");
        txtpeopleTell.setText("");
        peoplejob_no.setSelectedIndex(0);
        txtweipeople.setText("");
        txtdespeople.setText("");
        co.viewTable("select * from people_view", peopleTable);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "ma hubtaa","xaqiijin",
                     JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
        String oper="delete";
        Date dl=new Date(jDatepeople.getDate().getTime());
        Date dl2=new Date(jDatepeeoplereg.getDate().getTime());
        String sql="call people_proc('"+idpep+"','"+txtpeopleName.getText()+"', '"+txtpeopleTell.getText()+"',"
        + "'"+Gender+"','"+dl+"','"+txtweipeople.getText()+"',"
        + "'"+job+"','"+txtdespeople.getText()+"','"+dl2+"','"+oper+"')";
        co.setSQL(sql);
        btnsave.setEnabled(true);
        display();
        txtpeopleName.setText("");
        txtpeopleTell.setText("");
        peoplejob_no.setSelectedIndex(0);
        txtweipeople.setText("");
        txtdespeople.setText("");
        co.viewTable("select * from people_view", peopleTable);
        
    }//GEN-LAST:event_jLabel3MouseClicked
    }
    private void txtpeopleNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpeopleNameKeyPressed
        // TODO add your handling code here:
        
        char c= evt.getKeyChar();
        if(Character.isLetter(c)|| Character.isWhitespace(c)|| Character.isISOControl(c)){
            txtpeopleName.setEditable(true);
            showmess.setText("");
        }
        else
        {
            txtpeopleName.setEditable(false);
            showmess.setText("Only Letters Are Allowed");
        }
    }//GEN-LAST:event_txtpeopleNameKeyPressed

    private void showtellKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_showtellKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_showtellKeyPressed

    private void txtpeopleTellKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpeopleTellKeyPressed
         // TODO add your handling code here:
         char c= evt.getKeyChar();
        if(Character.isDigit(c)|| Character.isWhitespace(c)|| Character.isISOControl(c)){
            txtpeopleTell.setEditable(true);
            showtell.setText("");
        }
        else
        {
            txtpeopleTell.setEditable(false);
            showtell.setText("Only Digits Allowed");
        }
         
         
    }//GEN-LAST:event_txtpeopleTellKeyPressed

    private void txtdespeopleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdespeopleKeyPressed
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if(Character.isLetter(c)|| Character.isWhitespace(c)|| Character.isISOControl(c)){
            txtdespeople.setEditable(true);
            showdesc.setText("");
        }
        else
        {
            txtdespeople.setEditable(false);
            showdesc.setText("Only Letters Are Allowed");
        }
        
        
        
    }//GEN-LAST:event_txtdespeopleKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(people.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(people.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(people.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(people.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new people().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private necesario.LabelIcon btnclose;
    private javax.swing.JLabel btnsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton female;
    private com.toedter.calendar.JDateChooser jDatepeeoplereg;
    private com.toedter.calendar.JDateChooser jDatepeople;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton male;
    private javax.swing.JComboBox<String> peoplejob_no;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private javax.swing.JLabel showdesc;
    private javax.swing.JLabel showmess;
    private javax.swing.JLabel showtell;
    private app.bolivia.swing.JCTextField txtdespeople;
    private app.bolivia.swing.JCTextField txtpeopleName;
    private app.bolivia.swing.JCTextField txtpeopleSer;
    private app.bolivia.swing.JCTextField txtpeopleTell;
    private app.bolivia.swing.JCTextField txtweipeople;
    // End of variables declaration//GEN-END:variables
}
