/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team_management;

import java.awt.Color;
import java.sql.Date;
import javax.swing.JOptionPane;
import static team_management.dashboard.playerAggrimentsTable;

/**
 *
 * @author ALka Media
 */
public class player_agriment extends javax.swing.JFrame {
         Codes co=new Codes();
    public void display(){
}    String idpl="";
     String player ="";
     String team="";
     String cost="";
     String dur="";
     String des="";
     String cam3 = "";
     String cam4 = "";

    /**
     * Creates new form player_agriment
     */
    public player_agriment() {
        initComponents();
        display();
        co.fillCombo("SELECT pepname as  laqab FROM people",playerpeople_no,"laqab");
        co.fillCombo("SELECT teamsName as  nn FROM teams",playerteam_no,"nn");
    }
    public boolean validation(){
        if(txtcostplayer.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Cost");
            return false;
        }
        return true;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnclose = new necesario.LabelIcon();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtplayerdes = new app.bolivia.swing.JCTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcostplayer = new app.bolivia.swing.JCTextField();
        jLabel14 = new javax.swing.JLabel();
        txtplayerdur = new app.bolivia.swing.JCTextField();
        jDateplayer_agg = new com.toedter.calendar.JDateChooser();
        playerteam_no = new javax.swing.JComboBox<>();
        playerpeople_no = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtserplayer = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnclose.setBackground(new java.awt.Color(0, 153, 153));
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FORWARD);
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncloseMouseExited(evt);
            }
        });
        jPanel2.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/READY5.png"))); // NOI18N
        jLabel1.setText("Player Agriment");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 460, 90));

        jLabel6.setBackground(new java.awt.Color(0, 153, 153));
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 90));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("AggDate");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 90, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("peopleNo");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 90, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Description");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 110, 30));

        txtplayerdes.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtplayerdes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtplayerdes.setPhColor(new java.awt.Color(0, 102, 102));
        txtplayerdes.setPlaceholder("Enter Desc");
        txtplayerdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplayerdesActionPerformed(evt);
            }
        });
        jPanel2.add(txtplayerdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 210, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("TeamNo");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("Cost");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 80, 30));

        txtcostplayer.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtcostplayer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtcostplayer.setPhColor(new java.awt.Color(0, 102, 102));
        txtcostplayer.setPlaceholder("Enter Cost");
        txtcostplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcostplayerActionPerformed(evt);
            }
        });
        jPanel2.add(txtcostplayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 210, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("Duretion");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 90, 30));

        txtplayerdur.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtplayerdur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtplayerdur.setPhColor(new java.awt.Color(0, 102, 102));
        txtplayerdur.setPlaceholder("Enter Duretion");
        txtplayerdur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplayerdurActionPerformed(evt);
            }
        });
        jPanel2.add(txtplayerdur, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 210, 40));

        jDateplayer_agg.setForeground(new java.awt.Color(0, 102, 102));
        jDateplayer_agg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jDateplayer_agg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 210, 40));

        playerteam_no.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        playerteam_no.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Team" }));
        playerteam_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerteam_noActionPerformed(evt);
            }
        });
        jPanel2.add(playerteam_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 210, 40));

        playerpeople_no.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        playerpeople_no.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Player" }));
        playerpeople_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerpeople_noActionPerformed(evt);
            }
        });
        jPanel2.add(playerpeople_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 210, 40));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (21).png"))); // NOI18N
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 90, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (22).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 110, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (25).png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 110, 40));

        txtserplayer.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtserplayer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtserplayer.setPhColor(new java.awt.Color(0, 102, 102));
        txtserplayer.setPlaceholder("Enter Duretion");
        txtserplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserplayerActionPerformed(evt);
            }
        });
        jPanel2.add(txtserplayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 180, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (26).png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/people1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 490, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
         // TODO add your handling code here:
        //d.setVisible(true);
        this.hide();
        
    }//GEN-LAST:event_btncloseMouseClicked

    private void txtplayerdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplayerdesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplayerdesActionPerformed

    private void txtcostplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcostplayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcostplayerActionPerformed

    private void txtplayerdurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplayerdurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplayerdurActionPerformed

    private void btncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        btnclose.setBackground(clr);
        
    }//GEN-LAST:event_btncloseMouseEntered

    private void btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        btnclose.setBackground(clr);
    }//GEN-LAST:event_btncloseMouseExited

    private void playerpeople_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerpeople_noActionPerformed
        // TODO add your handling code here:
        try{ 
          co.search("SELECT * FROM people WHERE pepname='"+playerpeople_no.getSelectedItem()+"'");
         if(co.rs.next()){
             player=co.rs.getString("people_no");
             playerteam_no.setSelectedItem(cam3);
             
         }
          }
       catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex.getMessage());
       }
      
    }//GEN-LAST:event_playerpeople_noActionPerformed

    private void playerteam_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerteam_noActionPerformed
        // TODO add your handling code here:
        
        try{ 
          co.search("SELECT * FROM teams WHERE teamsName='"+playerteam_no.getSelectedItem()+"'");
         if(co.rs.next()){
             team=co.rs.getString("team_no");
             playerpeople_no.setSelectedItem(cam4);
             
         }
          } 
       catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex.getMessage());
       }
        
        
    }//GEN-LAST:event_playerteam_noActionPerformed

    private void txtserplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserplayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserplayerActionPerformed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
        
        String oper="insert";
        Date dl=new Date(jDateplayer_agg.getDate().getTime());
        String sql="call playerAggriments_proc(null,'"+player+"', '"+team+"','"+dl+"','"+txtcostplayer.getText()+"','"+txtplayerdur.getText()+"','"+txtplayerdes.getText()+"','"+oper+"')";
//      co.setSQL(sql);
      display();
    co.setSQL(sql);
   //txtser.setText(sql);
   playerteam_no.setSelectedIndex(0);
    playerpeople_no.setSelectedIndex(0);
    txtcostplayer.setText("");
    txtplayerdur.setText("");
    txtplayerdes.setText("");  
    co.viewTable("select * from player_agrement_view",playerAggrimentsTable);
        
    }//GEN-LAST:event_btnSaveMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        String oper="update";
        Date dl=new Date(jDateplayer_agg.getDate().getTime());
        String sql="call playerAggriments_proc('"+idpl+"','"+player+"', '"+team+"','"+dl+"','"+txtcostplayer.getText()+"','"+txtplayerdur.getText()+"','"+txtplayerdes.getText()+"','"+oper+"')";
//      co.setSQL(sql);
      display();
    co.setSQL(sql);
   //txtser.setText(sql);
   playerteam_no.setSelectedIndex(0);
    playerpeople_no.setSelectedIndex(0);
    txtcostplayer.setText("");
    txtplayerdur.setText("");
    txtplayerdes.setText("");
    co.viewTable("select * from player_agrement_view",playerAggrimentsTable);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        String oper="delete";
        Date dl=new Date(jDateplayer_agg.getDate().getTime());
        String sql="call playerAggriments_proc('"+idpl+"','"+player+"', '"+team+"','"+dl+"','"+txtcostplayer.getText()+"','"+txtplayerdur.getText()+"','"+txtplayerdes.getText()+"','"+oper+"')";
//      co.setSQL(sql);
      display();
    co.setSQL(sql);
    playerteam_no.setSelectedIndex(0);
    playerpeople_no.setSelectedIndex(0);
    txtcostplayer.setText("");
    txtplayerdur.setText("");
    txtplayerdes.setText("");
    co.viewTable("select * from player_agrement_view",playerAggrimentsTable);
    
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        
        String sql = "SELECT pa.pl_no, pep.pepname as qof, tm.teamsName as naadiyada, pa.agg_dadte taariiq, pa.cost as money, "
                + "pa.duration as xili,pa.descriptiion as fahfhin FROM player_agrement pa ,teams tm, people pep  "
                + "WHERE pa.people_no = pep.people_no and pa.team_no = tm.team_no and pa.pl_no='"+txtserplayer.getText() + "'";
        co.search(sql);
        try {
            if (co.rs.next()) {
                idpl = co.rs.getString("pl_no");

                txtcostplayer.setText(co.rs.getString("money"));
                txtplayerdur.setText(co.rs.getString("xili"));
                txtplayerdes.setText(co.rs.getString("fahfhin"));
                jDateplayer_agg.setDate(co.rs.getDate("taariiq"));
               cam4=co.rs.getString("qof");
             playerteam_no.setSelectedItem(co.rs.getString("naadiyada"));
                btnSave.setEnabled(false);
                txtserplayer.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Xogtaan Lama Helin");
            }
            txtserplayer.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(player_agriment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(player_agriment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(player_agriment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(player_agriment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new player_agriment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSave;
    private necesario.LabelIcon btnclose;
    private com.toedter.calendar.JDateChooser jDateplayer_agg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> playerpeople_no;
    private javax.swing.JComboBox<String> playerteam_no;
    private app.bolivia.swing.JCTextField txtcostplayer;
    private app.bolivia.swing.JCTextField txtplayerdes;
    private app.bolivia.swing.JCTextField txtplayerdur;
    private app.bolivia.swing.JCTextField txtserplayer;
    // End of variables declaration//GEN-END:variables
}
