
package team_management;

import java.awt.Color;
import javax.swing.JOptionPane;
import static team_management.dashboard.teamTable;

/**
 *
 * @author ALka Media
 */
public class teams extends javax.swing.JFrame {
Codes co=new Codes();
    public void display(){
}    String idte="";
     String oper="";
    /**
     * Creates new form teams
     */
    public teams() {
        initComponents();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSTextFieldIconOne1 = new RSMaterialComponent.RSTextFieldIconOne();
        rSButtonIcon_new1 = new newscomponents.RSButtonIcon_new();
        jPanel1 = new javax.swing.JPanel();
        btnclose = new necesario.LabelIcon();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rSLabelTextIcon5 = new RSMaterialComponent.RSLabelTextIcon();
        txtteamName = new RSMaterialComponent.RSTextFieldTwo();
        rSLabelTextIcon2 = new RSMaterialComponent.RSLabelTextIcon();
        txtteamDescription = new RSMaterialComponent.RSTextFieldTwo();
        txtser = new RSMaterialComponent.RSTextFieldIconOne();
        jLabel3 = new javax.swing.JLabel();
        btnsave = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        rSTextFieldIconOne1.setBackground(new java.awt.Color(0, 153, 153));
        rSTextFieldIconOne1.setForeground(new java.awt.Color(255, 255, 255));
        rSTextFieldIconOne1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rSTextFieldIconOne1.setBorderColor(new java.awt.Color(255, 255, 255));
        rSTextFieldIconOne1.setColorIcon(new java.awt.Color(255, 255, 255));
        rSTextFieldIconOne1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSTextFieldIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSTextFieldIconOne1.setPhColor(new java.awt.Color(204, 204, 204));
        rSTextFieldIconOne1.setPlaceholder("Type Here To Search");
        rSTextFieldIconOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldIconOne1ActionPerformed(evt);
            }
        });

        rSButtonIcon_new1.setBackground(new java.awt.Color(0, 102, 102));
        rSButtonIcon_new1.setText("Search");
        rSButtonIcon_new1.setActionCommand("Save");
        rSButtonIcon_new1.setBackgroundHover(new java.awt.Color(0, 153, 153));
        rSButtonIcon_new1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnclose.setBackground(new java.awt.Color(0, 102, 102));
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR);
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncloseMouseExited(evt);
            }
        });
        jPanel1.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 30, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/READY11.png"))); // NOI18N
        jLabel2.setText("    Add Teams");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 410, 90));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 100));

        rSLabelTextIcon5.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelTextIcon5.setText("TeamName");
        rSLabelTextIcon5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rSLabelTextIcon5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);
        jPanel1.add(rSLabelTextIcon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 130, 40));

        txtteamName.setForeground(new java.awt.Color(0, 0, 0));
        txtteamName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtteamName.setBorderColor(new java.awt.Color(255, 255, 255));
        txtteamName.setPhColor(new java.awt.Color(0, 102, 102));
        txtteamName.setPlaceholder("Enter Team_Name");
        jPanel1.add(txtteamName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 210, -1));

        rSLabelTextIcon2.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelTextIcon2.setText("Description");
        rSLabelTextIcon2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rSLabelTextIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DESCRIPTION);
        jPanel1.add(rSLabelTextIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 130, 40));

        txtteamDescription.setForeground(new java.awt.Color(0, 0, 0));
        txtteamDescription.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtteamDescription.setBorderColor(new java.awt.Color(255, 255, 255));
        txtteamDescription.setPhColor(new java.awt.Color(0, 102, 102));
        txtteamDescription.setPlaceholder("Enter Desc");
        jPanel1.add(txtteamDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 210, -1));

        txtser.setForeground(new java.awt.Color(255, 255, 255));
        txtser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtser.setBorderColor(new java.awt.Color(255, 255, 255));
        txtser.setColorIcon(new java.awt.Color(255, 255, 255));
        txtser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtser.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtser.setPhColor(new java.awt.Color(0, 153, 153));
        txtser.setPlaceholder("Type Here To Search");
        txtser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserActionPerformed(evt);
            }
        });
        jPanel1.add(txtser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 190, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (26).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 100, 50));

        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (21).png"))); // NOI18N
        btnsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsaveMouseClicked(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 90, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (22).png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 110, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/button (25).png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 110, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team_management/jobimage2.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 470, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSTextFieldIconOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldIconOne1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldIconOne1ActionPerformed

    private void txtserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserActionPerformed

    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
         // TODO add your handling code here:
        this.hide();
        
    }//GEN-LAST:event_btncloseMouseClicked

    private void btncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseEntered

        Color clr = new Color(0,153,153);
        btnclose.setBackground(clr);
    }//GEN-LAST:event_btncloseMouseEntered

    private void btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        btnclose.setBackground(clr);
    }//GEN-LAST:event_btncloseMouseExited

    private void btnsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseClicked
        // TODO add your handling code here:
        
         String oper="insert";
         String sql="call teams_proc(null,'"+txtteamName.getText()+"', '"+txtteamDescription.getText()+"','"+oper+"')";
      co.setSQL(sql);
      display();
      txtteamName.setText("");  txtteamDescription.setText("");
        co.viewTable("select * from teams",teamTable);
        
    }//GEN-LAST:event_btnsaveMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        
         String oper="update";
        String sql="call teams_proc('"+idte+"','"+txtteamName.getText()+"', '"+txtteamDescription.getText()+"','"+oper+"')";
      co.setSQL(sql);
      display();
      txtteamName.setText("");  txtteamDescription.setText("");
      btnsave.setEnabled(true);
    co.viewTable("select * from teams",teamTable);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "ma hubtaa","xaqiijin",
                     JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
         String oper="delete";
        String sql="call teams_proc('"+idte+"','"+txtteamName.getText()+"', '"+txtteamDescription.getText()+"','"+oper+"')";
             
      co.setSQL(sql);
      display();
      txtteamName.setText("");  txtteamDescription.setText("");  
      co.viewTable("select * from teams",teamTable);
             }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        
         String sql="select * from teams where teamsName='"+txtser.getText()+"' or team_no='"+txtser.getText()+"'";
     co.search(sql);
     try{
         if(co.rs.next()){
             idte=co.rs.getString("team_no");
             txtteamName.setText(co.rs.getString("teamsName"));
             txtteamDescription.setText(co.rs.getString("Description"));
             btnsave.setEnabled(false);
             txtser.setText("");
         }
         else
             JOptionPane.showMessageDialog(null, "Xogtaan Lama Helin");
            txtser.setText("");
     }catch(Exception ex){
         JOptionPane.showMessageDialog(null, ex.getMessage());
     }
        
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teams().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private necesario.LabelIcon btnclose;
    private javax.swing.JLabel btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private newscomponents.RSButtonIcon_new rSButtonIcon_new1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon2;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon5;
    private RSMaterialComponent.RSTextFieldIconOne rSTextFieldIconOne1;
    private RSMaterialComponent.RSTextFieldIconOne txtser;
    private RSMaterialComponent.RSTextFieldTwo txtteamDescription;
    private RSMaterialComponent.RSTextFieldTwo txtteamName;
    // End of variables declaration//GEN-END:variables
}
